CREATE TABLE meshes(
    id INTEGER NOT NULL PRIMARY KEY,

    name TEXT NOT NULL UNIQUE,
    scale_x REAL NOT NULL DEFAULT 0,
    scale_y REAL NOT NULL DEFAULT 0,
    scale_z REAL NOT NULL DEFAULT 0,
    pos_x REAL NOT NULL DEFAULT 0,
    pos_y REAL NOT NULL DEFAULT 0,
    pos_z REAL NOT NULL DEFAULT 0,
    rot_x REAL NOT NULL DEFAULT 0,
    rot_y REAL NOT NULL DEFAULT 0,
    rot_z REAL NOT NULL DEFAULT 0
);

CREATE TABLE scenes(
    id INTEGER NOT NULL PRIMARY KEY,

    name TEXT NOT NULL UNIQUE,
    cam_pos_x REAL NOT NULL DEFAULT 0,
    cam_pos_y REAL NOT NULL DEFAULT 0,
    cam_pos_z REAL NOT NULL DEFAULT 0,
    cam_rot_x REAL NOT NULL DEFAULT 0,
    cam_rot_y REAL NOT NULL DEFAULT 0,
    cam_rot_z REAL NOT NULL DEFAULT 0,
    cam_zoom REAL NOT NULL DEFAULT 0,
    ctrl_x REAL NOT NULL DEFAULT 0,
    ctrl_y REAL NOT NULL DEFAULT 0,
    ctrl_z REAL NOT NULL DEFAULT 0
);
