import type { Options } from "@hey-api/client-fetch";
import type {
  DelPlaylistData,
  DelPlaylistError,
  DelPlaylistResponse,
  DelScheduleData,
  DelScheduleError,
  DelScheduleResponse,
  DelSequenceData,
  DelSequenceError,
  DelSequenceResponse,
  FileUploadData,
  FileUploadError,
  FileUploadResponse,
  FppCommandData,
  FppCommandError,
  FppCommandResponse,
  GetDisplayError,
  GetDisplayResponse,
  GetLogData,
  GetLogError,
  GetLogResponse,
  GetLogsError,
  GetLogsResponse,
  GetModelsError,
  GetModelsResponse,
  GetOutputsError,
  GetOutputsResponse,
  GetPlaylistData,
  GetPlaylistError,
  GetPlaylistResponse,
  GetScheduleData,
  GetScheduleError,
  GetScheduleResponse,
  GetSchedulerStatusError,
  GetSchedulerStatusResponse,
  GetSequenceData,
  GetSequenceError,
  GetSequenceMetaData,
  GetSequenceMetaError,
  GetSequenceMetaResponse,
  GetSequenceResponse,
  ListPlaylistsError,
  ListPlaylistsNumberedError,
  ListPlaylistsNumberedResponse,
  ListPlaylistsResponse,
  ListSchedulesError,
  ListSchedulesResponse,
  ListSequencesError,
  ListSequencesResponse,
  NewPlaylistData,
  NewPlaylistError,
  NewPlaylistResponse,
  NewScheduleData,
  NewScheduleError,
  NewScheduleResponse,
  StartSchedulerError,
  StartSchedulerResponse,
  StopSchedulerError,
  StopSchedulerResponse,
  SystemInfoError,
  SystemInfoResponse,
  UpdatePlaylistData,
  UpdatePlaylistError,
  UpdatePlaylistResponse,
  UpdateScheduleData,
  UpdateScheduleError,
  UpdateScheduleResponse,
  UploadDisplayData,
  UploadDisplayError,
  UploadDisplayResponse,
  UploadModelsData,
  UploadModelsError,
  UploadModelsResponse,
  UploadOutputsData,
  UploadOutputsError,
  UploadOutputsResponse,
} from "./types.gen";

import { createClient, createConfig, formDataBodySerializer } from "@hey-api/client-fetch";

// This file is auto-generated by @hey-api/openapi-ts

export const client = createClient(createConfig());

/**
 * Retrieve outputs.json
 * Download the outputs in JSON format
 */
export const getOutputs = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetOutputsResponse, GetOutputsError, ThrowOnError>({
    ...options,
    url: "/api/channel/output/universeOutputs",
  });
};

/**
 * Upload outputs.json
 * Upload the outputs in JSON format
 */
export const uploadOutputs = <ThrowOnError extends boolean = false>(
  options: Options<UploadOutputsData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    UploadOutputsResponse,
    UploadOutputsError,
    ThrowOnError
  >({
    ...options,
    url: "/api/channel/output/universeOutputs",
  });
};

/**
 * Retrieve VirtualDisplayMap
 * Download the VirtualDisplayMap
 */
export const getDisplay = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetDisplayResponse, GetDisplayError, ThrowOnError>({
    ...options,
    url: "/api/configfile/virtualdisplaymap",
  });
};

/**
 * Upload VirtualDisplayMap
 * Upload the VirtualDisplayMap
 */
export const uploadDisplay = <ThrowOnError extends boolean = false>(
  options: Options<UploadDisplayData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    UploadDisplayResponse,
    UploadDisplayError,
    ThrowOnError
  >({
    ...options,
    url: "/api/configfile/virtualdisplaymap",
  });
};

/**
 * Get a specific log
 */
export const getLog = <ThrowOnError extends boolean = false>(
  options: Options<GetLogData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetLogResponse, GetLogError, ThrowOnError>({
    ...options,
    url: "/api/log/{name}",
  });
};

/**
 * Get log filenames
 */
export const getLogs = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetLogsResponse, GetLogsError, ThrowOnError>({
    ...options,
    url: "/api/logs",
  });
};

/**
 * Retrieve models.json
 * Download the models in JSON format
 */
export const getModels = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetModelsResponse, GetModelsError, ThrowOnError>({
    ...options,
    url: "/api/models",
  });
};

/**
 * Upload models.json
 * Upload the models in JSON format
 */
export const uploadModels = <ThrowOnError extends boolean = false>(
  options: Options<UploadModelsData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    UploadModelsResponse,
    UploadModelsError,
    ThrowOnError
  >({
    ...options,
    url: "/api/models",
  });
};

/**
 * New playlist
 * Create a new playlist
 */
export const newPlaylist = <ThrowOnError extends boolean = false>(
  options: Options<NewPlaylistData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<NewPlaylistResponse, NewPlaylistError, ThrowOnError>({
    ...options,
    url: "/api/playlist",
  });
};

/**
 * Get a playlist
 * Read back a playlist
 */
export const getPlaylist = <ThrowOnError extends boolean = false>(
  options: Options<GetPlaylistData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetPlaylistResponse, GetPlaylistError, ThrowOnError>({
    ...options,
    url: "/api/playlist/{playlist}",
  });
};

/**
 * Update a playlist
 * Create or update the given playlist
 */
export const updatePlaylist = <ThrowOnError extends boolean = false>(
  options: Options<UpdatePlaylistData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    UpdatePlaylistResponse,
    UpdatePlaylistError,
    ThrowOnError
  >({
    ...options,
    url: "/api/playlist/{playlist}",
  });
};

/**
 * Delete a playlist
 * Delete the given playlist
 */
export const delPlaylist = <ThrowOnError extends boolean = false>(
  options: Options<DelPlaylistData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    DelPlaylistResponse,
    DelPlaylistError,
    ThrowOnError
  >({
    ...options,
    url: "/api/playlist/{playlist}",
  });
};

/**
 * List playlists
 * List the name of all playlists
 */
export const listPlaylists = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListPlaylistsResponse,
    ListPlaylistsError,
    ThrowOnError
  >({
    ...options,
    url: "/api/playlists",
  });
};

/**
 * List playlists with ID
 * List the playlists with their ID
 */
export const listPlaylistsNumbered = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListPlaylistsNumberedResponse,
    ListPlaylistsNumberedError,
    ThrowOnError
  >({
    ...options,
    url: "/api/playlists/numbered",
  });
};

/**
 * New schedule
 * Create a new schedule
 */
export const newSchedule = <ThrowOnError extends boolean = false>(
  options: Options<NewScheduleData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<NewScheduleResponse, NewScheduleError, ThrowOnError>({
    ...options,
    url: "/api/schedule",
  });
};

/**
 * Get a schedule
 * Read back a schedule
 */
export const getSchedule = <ThrowOnError extends boolean = false>(
  options: Options<GetScheduleData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetScheduleResponse, GetScheduleError, ThrowOnError>({
    ...options,
    url: "/api/schedule/{schedule}",
  });
};

/**
 * Update a schedule
 * Create or update the given schedule
 */
export const updateSchedule = <ThrowOnError extends boolean = false>(
  options: Options<UpdateScheduleData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    UpdateScheduleResponse,
    UpdateScheduleError,
    ThrowOnError
  >({
    ...options,
    url: "/api/schedule/{schedule}",
  });
};

/**
 * Delete a schedule
 * Delete the given schedule
 */
export const delSchedule = <ThrowOnError extends boolean = false>(
  options: Options<DelScheduleData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    DelScheduleResponse,
    DelScheduleError,
    ThrowOnError
  >({
    ...options,
    url: "/api/schedule/{schedule}",
  });
};

/**
 * Get the scheduler status
 */
export const getSchedulerStatus = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetSchedulerStatusResponse,
    GetSchedulerStatusError,
    ThrowOnError
  >({
    ...options,
    url: "/api/scheduler",
  });
};

/**
 * Start the scheduler
 */
export const startScheduler = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    StartSchedulerResponse,
    StartSchedulerError,
    ThrowOnError
  >({
    ...options,
    url: "/api/scheduler/start",
  });
};

/**
 * Stop the scheduler
 */
export const stopScheduler = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    StopSchedulerResponse,
    StopSchedulerError,
    ThrowOnError
  >({
    ...options,
    url: "/api/scheduler/stop",
  });
};

/**
 * List schedules
 * List the name of all schedules
 */
export const listSchedules = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListSchedulesResponse,
    ListSchedulesError,
    ThrowOnError
  >({
    ...options,
    url: "/api/schedules",
  });
};

/**
 * Get a sequence
 * Download a sequence file
 */
export const getSequence = <ThrowOnError extends boolean = false>(
  options: Options<GetSequenceData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetSequenceResponse, GetSequenceError, ThrowOnError>({
    ...options,
    url: "/api/sequence/{filename}",
  });
};

/**
 * Delete a sequence
 * Remove a sequence file
 */
export const delSequence = <ThrowOnError extends boolean = false>(
  options: Options<DelSequenceData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    DelSequenceResponse,
    DelSequenceError,
    ThrowOnError
  >({
    ...options,
    url: "/api/sequence/{filename}",
  });
};

/**
 * Get a sequence's metadata
 * Get the metadata belonging to a sequence
 */
export const getSequenceMeta = <ThrowOnError extends boolean = false>(
  options: Options<GetSequenceMetaData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetSequenceMetaResponse,
    GetSequenceMetaError,
    ThrowOnError
  >({
    ...options,
    url: "/api/sequence/{filename}/meta",
  });
};

/**
 * List all sequences
 * List all sequence files
 */
export const listSequences = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListSequencesResponse,
    ListSequencesError,
    ThrowOnError
  >({
    ...options,
    url: "/api/sequences",
  });
};

/**
 * Get system info.
 * Get the high-level system information. This endpoint is used
 * to simulate FPP and make us discoverable by other software such
 * as xLights. Some values are hard-coded to ensure compatibility.
 */
export const systemInfo = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<SystemInfoResponse, SystemInfoError, ThrowOnError>({
    ...options,
    url: "/api/system/info",
  });
};

/**
 * Upload a file
 * Accepts fseq sequences or media files such as
 * images and videos. The uploaded file is automatically
 * sorted into the relevant upload directory so a call to
 * `moveFile` isn't required and will be ignore.
 */
export const fileUpload = <ThrowOnError extends boolean = false>(
  options: Options<FileUploadData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<FileUploadResponse, FileUploadError, ThrowOnError>({
    ...options,
    ...formDataBodySerializer,
    headers: {
      "Content-Type": null,
      ...options?.headers,
    },
    url: "/api/upload",
  });
};

/**
 * Run an FPP Command
 * This method isn't really implemented. The only command you
 * can issue is `moveFile` and all that really does is check
 * whether a file exists or not - it doesn't move it because
 * that's handled at upload time.
 */
export const fppCommand = <ThrowOnError extends boolean = false>(
  options: Options<FppCommandData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<FppCommandResponse, FppCommandError, ThrowOnError>({
    ...options,
    url: "/fppxml.php",
  });
};
