// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export const Action = {
  NO_ACTION: "no_action",
  SCHEDULE: "schedule",
  PLAYLIST: "playlist",
  SEQUENCE: "sequence",
  STOP: "stop",
} as const;

export type Action = (typeof Action)[keyof typeof Action];

export type BinaryFile = Blob | File;

export type Button = {
  action: Action;
  action_target: string;
  battery: number;
  error: string;
  id: number;
  input: boolean;
  last: number;
  now: number;
  status: string;
};

export type ChannelOutput = {
  channelCount: number;
  enabled: boolean;
  startChannel: number;
  timeout: number;
  type: string;
  universes: Array<Universe>;
};

export type Channels = {
  channelOutputs: Array<ChannelOutput>;
};

export type Chase = {
  color: Color;
  width: number;
};

export type Color = {
  b: number;
  g: number;
  r: number;
};

export type DiskUtilization = {
  Media: FreeTotal;
  Root: FreeTotal;
};

export type FileUpload = {
  /**
   * File or files to upload
   */
  myfile: Blob | File;
};

export type FreeTotal = {
  Free: number;
  Total: number;
};

export type Mesh = {
  id: number;
  name: string;
  pos_x: number;
  pos_y: number;
  pos_z: number;
  rot_x: number;
  rot_y: number;
  rot_z: number;
  scale_x: number;
  scale_y: number;
  scale_z: number;
};

export type Model = {
  ChannelCount: number;
  ChannelCountPerNode: number;
  Name: string;
  Orientation: string;
  StartChannel: number;
  StartCorner: string;
  StrandsPerString: number;
  StringCount: number;
  Type: string;
  xLights: boolean;
};

export type Models = {
  models: Array<Model>;
};

export type NewButton = {
  action?: null | Action;
  action_target?: string | null;
  battery: number;
  error: string;
  input: boolean;
  last: number;
  now?: number | null;
  status: string;
};

export type NewMesh = {
  name: string;
  pos_x: number;
  pos_y: number;
  pos_z: number;
  rot_x: number;
  rot_y: number;
  rot_z: number;
  scale_x: number;
  scale_y: number;
  scale_z: number;
};

export type NewScene = {
  cam_pos_x: number;
  cam_pos_y: number;
  cam_pos_z: number;
  cam_rot_x: number;
  cam_rot_y: number;
  cam_rot_z: number;
  cam_zoom: number;
  ctrl_x: number;
  ctrl_y: number;
  ctrl_z: number;
  name: string;
};

export type NumberedPlaylist = {
  id: number;
  name: string;
};

export const Pattern = {
  SPECTRAL: "spectral",
  BLUES: "blues",
  GREENS: "greens",
  GREYS: "greys",
  ORANGES: "oranges",
  PURPLES: "purples",
  REDS: "reds",
  TURBO: "turbo",
  VIRIDIS: "viridis",
  INFERNO: "inferno",
  MAGMA: "magma",
  PLASMA: "plasma",
  CIVIDIS: "cividis",
  WARM: "warm",
  COOL: "cool",
  CUBE_HELIX: "cube_helix",
  SINEBOW: "sinebow",
  RAINBOW: "rainbow",
} as const;

export type Pattern = (typeof Pattern)[keyof typeof Pattern];

export type PlayerState =
  | "schedule"
  | {
      playlist: string;
    }
  | {
      sequence: string;
    }
  | {
      test: TestSpec;
    }
  | "stop";

export const PlayerStatus = {
  SCHEDULER: "scheduler",
  PLAYLIST: "playlist",
  SEQUENCE: "sequence",
  TESTING: "testing",
  STOPPED: "stopped",
} as const;

export type PlayerStatus = (typeof PlayerStatus)[keyof typeof PlayerStatus];

export type Playlist = {
  desc: string;
  empty: boolean;
  leadIn: Array<PlaylistEntry>;
  leadOut: Array<PlaylistEntry>;
  loopCount: number;
  mainPlaylist: Array<PlaylistEntry>;
  name?: string | null;
  playlistInfo?: null | PlaylistInfo;
  random: boolean;
  repeat: boolean;
  version: number;
};

export type PlaylistEntry = {
  duration?: number | null;
  enabled: boolean;
  playOnce: boolean;
  sequenceName: string;
  type: string;
};

export type PlaylistInfo = {
  total_duration: number;
  total_items: number;
};

export type Scene = {
  cam_pos_x: number;
  cam_pos_y: number;
  cam_pos_z: number;
  cam_rot_x: number;
  cam_rot_y: number;
  cam_rot_z: number;
  cam_zoom: number;
  ctrl_x: number;
  ctrl_y: number;
  ctrl_z: number;
  id: number;
  name: string;
};

export type Schedule = {
  enabled: boolean;
  end_date: string;
  end_time: string;
  friday: boolean;
  monday: boolean;
  name: string;
  playlist_id: number;
  saturday: boolean;
  start_date: string;
  start_time: string;
  sunday: boolean;
  thursday: boolean;
  tuesday: boolean;
  wednesday: boolean;
};

export type Sequence =
  | {
      solid: Color;
    }
  | {
      chase: Chase;
    }
  | {
      pattern: Pattern;
    }
  | {
      moving_pattern: Pattern;
    }
  | {
      custom_pattern: Array<Color>;
    }
  | {
      custom_moving_pattern: Array<Color>;
    };

export type SequenceMeta = {
  /**
   * Number of channels
   */
  ChannelCount: number;
  /**
   * ID of the sequence (Likely the creation timestamp)
   */
  ID: string;
  /**
   * Name of the sequence
   */
  Name: string;
  /**
   * Number of framess
   */
  NumFrames: number;
  /**
   * Step time in milliseconds
   */
  StepTime: number;
  /**
   * Any additional variables
   */
  variableHeaders: {
    [key: string]: string;
  };
};

export type Status = {
  /**
   * What went wrong
   */
  error?: string | null;
  /**
   * Status
   */
  status: string;
};

export type SystemInfo = {
  /**
   * The CVS branch we're running on
   */
  Branch: string;
  /**
   * The description of this system
   */
  HostDescription: string;
  /**
   * Hostname of the system
   */
  HostName: string;
  /**
   * The IP addresses for this host
   */
  IPs: Array<string>;
  /**
   * The kernel version
   */
  Kernel: string;
  /**
   * The version for CVS
   */
  LocalGitVersion: string;
  /**
   * The logo of this system
   */
  Logo: string;
  /**
   * The mode of this system
   */
  Mode: string;
  /**
   * The OS Release
   */
  OSRelease: string;
  /**
   * The OS Version
   */
  OSVersion: string;
  /**
   * The platform we're running on
   */
  Platform: string;
  /**
   * The latest upstream CVS version
   */
  RemoteGitVersion: string;
  /**
   * Any additional contex to the platform
   */
  SubPlatform: string;
  /**
   * The location of updates
   */
  UpgradeSource: string;
  /**
   * The current system utilization
   */
  Utilization: SystemUtilization;
  /**
   * The platform we're running on
   */
  Variant: string;
  /**
   * The version of "FPPF" we're runnnig
   */
  Version: string;
  /**
   * The background color to use in the UI
   */
  backgroundColor: string;
  /**
   * Is multisync supported
   */
  multisync: boolean;
  /**
   * The type of system
   */
  typeId: number;
  /**
   * The persistent UUID for this system
   */
  uuid: string;
};

export type SystemUtilization = {
  CPU: number;
  Disk: DiskUtilization;
  Memory: number;
  Uptime: string;
};

export type TestSpec = {
  step_ms: number;
  tests: {
    [key: string]: Sequence;
  };
};

export type TimezoneConfig = {
  /**
   * ISO 8601 formatted time string
   */
  time: string;
  /**
   * Timezone name (e.g., "America/New_York")
   */
  timezone: string;
};

export type Universe = {
  active: boolean;
  address: string;
  channelCount: number;
  deDuplicate: boolean;
  description: string;
  id: number;
  monitor: boolean;
  priority: number;
  startChannel: number;
  type: number;
};

export type NewButtonData = {
  body: NewButton;
  path?: never;
  query?: never;
  url: "/api/button";
};

export type NewButtonErrors = {
  /**
   * Incomplete button supplied
   */
  422: Status;
  /**
   * Something went wrong
   */
  500: Status;
};

export type NewButtonError = NewButtonErrors[keyof NewButtonErrors];

export type NewButtonResponses = {
  /**
   * The button was created
   */
  201: Status;
};

export type NewButtonResponse = NewButtonResponses[keyof NewButtonResponses];

export type DelButtonData = {
  body?: never;
  path: {
    /**
     * The ID of the button
     */
    button: number;
  };
  query?: never;
  url: "/api/button/{button}";
};

export type DelButtonErrors = {
  /**
   * The button wasn't found
   */
  404: Status;
  /**
   * Something went wrong
   */
  500: Status;
};

export type DelButtonError = DelButtonErrors[keyof DelButtonErrors];

export type DelButtonResponses = {
  /**
   * The requested button was deleted
   */
  200: Status;
};

export type DelButtonResponse = DelButtonResponses[keyof DelButtonResponses];

export type GetButtonData = {
  body?: never;
  path: {
    /**
     * The ID of the button
     */
    button: number;
  };
  query?: never;
  url: "/api/button/{button}";
};

export type GetButtonErrors = {
  /**
   * Unknown button
   */
  404: Status;
  /**
   * Something went wrong
   */
  500: Status;
};

export type GetButtonError = GetButtonErrors[keyof GetButtonErrors];

export type GetButtonResponses = {
  /**
   * The requested button
   */
  200: Button;
};

export type GetButtonResponse = GetButtonResponses[keyof GetButtonResponses];

export type UpdateButtonData = {
  body: NewButton;
  path: {
    /**
     * The ID of the button
     */
    button: number;
  };
  query?: never;
  url: "/api/button/{button}";
};

export type UpdateButtonErrors = {
  /**
   * Incomplete button supplied
   */
  422: Status;
  /**
   * Something went wrong
   */
  500: Status;
};

export type UpdateButtonError = UpdateButtonErrors[keyof UpdateButtonErrors];

export type UpdateButtonResponses = {
  /**
   * The requested button was updated
   */
  200: Status;
};

export type UpdateButtonResponse = UpdateButtonResponses[keyof UpdateButtonResponses];

export type ListButtonsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/buttons";
};

export type ListButtonsErrors = {
  /**
   * Something went wrong
   */
  500: Status;
};

export type ListButtonsError = ListButtonsErrors[keyof ListButtonsErrors];

export type ListButtonsResponses = {
  /**
   * List of buttons
   */
  200: Array<Button>;
};

export type ListButtonsResponse = ListButtonsResponses[keyof ListButtonsResponses];

export type GetOutputsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/channel/output/universeOutputs";
};

export type GetOutputsErrors = {
  /**
   * Outputs not found
   */
  404: Status;
  /**
   * Something went wrong
   */
  500: Status;
};

export type GetOutputsError = GetOutputsErrors[keyof GetOutputsErrors];

export type GetOutputsResponses = {
  /**
   * Ouputs downloaded successfully
   */
  200: Channels;
};

export type GetOutputsResponse = GetOutputsResponses[keyof GetOutputsResponses];

export type UploadOutputsData = {
  body: Channels;
  path?: never;
  query?: never;
  url: "/api/channel/output/universeOutputs";
};

export type UploadOutputsErrors = {
  /**
   * Something went wrong
   */
  500: Status;
};

export type UploadOutputsError = UploadOutputsErrors[keyof UploadOutputsErrors];

export type UploadOutputsResponses = {
  /**
   * Outputs uploaded successfully
   */
  200: Status;
};

export type UploadOutputsResponse = UploadOutputsResponses[keyof UploadOutputsResponses];

export type SetTimezoneData = {
  body: TimezoneConfig;
  path?: never;
  query?: never;
  url: "/api/config/timezone";
};

export type SetTimezoneErrors = {
  /**
   * Invalid input
   */
  400: Status;
  /**
   * Insufficient privileges
   */
  403: Status;
  /**
   * Something went wrong
   */
  500: Status;
};

export type SetTimezoneError = SetTimezoneErrors[keyof SetTimezoneErrors];

export type SetTimezoneResponses = {
  /**
   * Time and timezone set successfully
   */
  200: Status;
};

export type SetTimezoneResponse = SetTimezoneResponses[keyof SetTimezoneResponses];

export type ListTimezonesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/config/timezones";
};

export type ListTimezonesErrors = {
  /**
   * Something went wrong
   */
  500: Status;
};

export type ListTimezonesError = ListTimezonesErrors[keyof ListTimezonesErrors];

export type ListTimezonesResponses = {
  /**
   * List of timezones
   */
  200: Array<string>;
};

export type ListTimezonesResponse = ListTimezonesResponses[keyof ListTimezonesResponses];

export type GetDisplayData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/configfile/virtualdisplaymap";
};

export type GetDisplayErrors = {
  /**
   * VirtualDisplayMap not found
   */
  404: Status;
  /**
   * Something went wrong
   */
  500: Status;
};

export type GetDisplayError = GetDisplayErrors[keyof GetDisplayErrors];

export type GetDisplayResponses = {
  /**
   * VirtualDisplayMap downloaded successfully
   */
  200: string;
};

export type GetDisplayResponse = GetDisplayResponses[keyof GetDisplayResponses];

export type UploadDisplayData = {
  body: Blob | File;
  path?: never;
  query?: never;
  url: "/api/configfile/virtualdisplaymap";
};

export type UploadDisplayErrors = {
  /**
   * Something went wrong
   */
  500: Status;
};

export type UploadDisplayError = UploadDisplayErrors[keyof UploadDisplayErrors];

export type UploadDisplayResponses = {
  /**
   * VDM uploaded successfully
   */
  200: Status;
};

export type UploadDisplayResponse = UploadDisplayResponses[keyof UploadDisplayResponses];

export type GetLogData = {
  body?: never;
  path: {
    /**
     * The name of the log to display
     */
    name: string;
  };
  query?: never;
  url: "/api/log/{name}";
};

export type GetLogErrors = {
  /**
   * Logging is disabled
   */
  400: Status;
  /**
   * Something went wrong
   */
  500: Status;
};

export type GetLogError = GetLogErrors[keyof GetLogErrors];

export type GetLogResponses = {
  /**
   * List of log filenames
   */
  200: string;
};

export type GetLogResponse = GetLogResponses[keyof GetLogResponses];

export type ListLogsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/logs";
};

export type ListLogsErrors = {
  /**
   * Something went wrong
   */
  500: Status;
};

export type ListLogsError = ListLogsErrors[keyof ListLogsErrors];

export type ListLogsResponses = {
  /**
   * List of log filenames
   */
  200: Array<string>;
};

export type ListLogsResponse = ListLogsResponses[keyof ListLogsResponses];

export type NewMeshData = {
  body: NewMesh;
  path?: never;
  query?: never;
  url: "/api/mesh";
};

export type NewMeshErrors = {
  /**
   * Incomplete mesh supplied
   */
  422: Status;
  /**
   * Something went wrong
   */
  500: Status;
};

export type NewMeshError = NewMeshErrors[keyof NewMeshErrors];

export type NewMeshResponses = {
  /**
   * The mesh was created
   */
  201: Status;
};

export type NewMeshResponse = NewMeshResponses[keyof NewMeshResponses];

export type DelMeshData = {
  body?: never;
  path: {
    /**
     * The name of the mesh
     */
    mesh: string;
  };
  query?: never;
  url: "/api/mesh/{mesh}";
};

export type DelMeshErrors = {
  /**
   * The mesh wasn't found
   */
  404: Status;
  /**
   * Something went wrong
   */
  500: Status;
};

export type DelMeshError = DelMeshErrors[keyof DelMeshErrors];

export type DelMeshResponses = {
  /**
   * The requested mesh was deleted
   */
  200: Status;
};

export type DelMeshResponse = DelMeshResponses[keyof DelMeshResponses];

export type DownloadMeshData = {
  body?: never;
  path: {
    /**
     * The name of the mesh
     */
    mesh: string;
  };
  query?: never;
  url: "/api/mesh/{mesh}";
};

export type DownloadMeshErrors = {
  /**
   * Unknown mesh
   */
  404: Status;
  /**
   * Something went wrong
   */
  500: Status;
};

export type DownloadMeshError = DownloadMeshErrors[keyof DownloadMeshErrors];

export type DownloadMeshResponses = {
  /**
   * The requested mesh
   */
  200: Blob | File;
};

export type DownloadMeshResponse = DownloadMeshResponses[keyof DownloadMeshResponses];

export type UpdateMeshData = {
  body: NewMesh;
  path: {
    /**
     * The name of the mesh
     */
    mesh: string;
  };
  query?: never;
  url: "/api/mesh/{mesh}";
};

export type UpdateMeshErrors = {
  /**
   * Incomplete mesh supplied
   */
  422: Status;
  /**
   * Something went wrong
   */
  500: Status;
};

export type UpdateMeshError = UpdateMeshErrors[keyof UpdateMeshErrors];

export type UpdateMeshResponses = {
  /**
   * The requested mesh was updated
   */
  200: Status;
};

export type UpdateMeshResponse = UpdateMeshResponses[keyof UpdateMeshResponses];

export type ListMeshesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/meshes";
};

export type ListMeshesErrors = {
  /**
   * Something went wrong
   */
  500: Status;
};

export type ListMeshesError = ListMeshesErrors[keyof ListMeshesErrors];

export type ListMeshesResponses = {
  /**
   * List of meshes
   */
  200: Array<Mesh>;
};

export type ListMeshesResponse = ListMeshesResponses[keyof ListMeshesResponses];

export type ListModelsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/models";
};

export type ListModelsErrors = {
  /**
   * Models not found
   */
  404: Status;
  /**
   * Something went wrong
   */
  500: Status;
};

export type ListModelsError = ListModelsErrors[keyof ListModelsErrors];

export type ListModelsResponses = {
  /**
   * Models downloaded successfully
   */
  200: Array<Model>;
};

export type ListModelsResponse = ListModelsResponses[keyof ListModelsResponses];

export type UploadModelsData = {
  body: Models;
  path?: never;
  query?: never;
  url: "/api/models";
};

export type UploadModelsErrors = {
  /**
   * Something went wrong
   */
  500: Status;
};

export type UploadModelsError = UploadModelsErrors[keyof UploadModelsErrors];

export type UploadModelsResponses = {
  /**
   * Models uploaded successfully
   */
  200: Status;
};

export type UploadModelsResponse = UploadModelsResponses[keyof UploadModelsResponses];

export type GetStatusData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/player";
};

export type GetStatusErrors = {
  /**
   * Something went wrong
   */
  500: Status;
};

export type GetStatusError = GetStatusErrors[keyof GetStatusErrors];

export type GetStatusResponses = {
  /**
   * Status of the scheduler
   */
  200: PlayerStatus;
};

export type GetStatusResponse = GetStatusResponses[keyof GetStatusResponses];

export type StartSchedulerData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/player/schedule";
};

export type StartSchedulerErrors = {
  /**
   * Something went wrong
   */
  500: Status;
};

export type StartSchedulerError = StartSchedulerErrors[keyof StartSchedulerErrors];

export type StartSchedulerResponses = {
  /**
   * Player started ok
   */
  200: Status;
};

export type StartSchedulerResponse = StartSchedulerResponses[keyof StartSchedulerResponses];

export type StopData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/player/stop";
};

export type StopErrors = {
  /**
   * Something went wrong
   */
  500: Status;
};

export type StopError = StopErrors[keyof StopErrors];

export type StopResponses = {
  /**
   * Player stopped ok
   */
  200: Status;
};

export type StopResponse = StopResponses[keyof StopResponses];

export type RunTestData = {
  body: TestSpec;
  path?: never;
  query?: never;
  url: "/api/player/test";
};

export type RunTestErrors = {
  /**
   * Something went wrong
   */
  500: Status;
};

export type RunTestError = RunTestErrors[keyof RunTestErrors];

export type RunTestResponses = {
  /**
   * Tests started ok
   */
  200: Status;
};

export type RunTestResponse = RunTestResponses[keyof RunTestResponses];

export type NewPlaylistData = {
  body: Playlist;
  path?: never;
  query?: never;
  url: "/api/playlist";
};

export type NewPlaylistErrors = {
  /**
   * Incomplete playlist supplied
   */
  422: Status;
  /**
   * Something went wrong
   */
  500: Status;
};

export type NewPlaylistError = NewPlaylistErrors[keyof NewPlaylistErrors];

export type NewPlaylistResponses = {
  /**
   * The playlist was created
   */
  201: Status;
};

export type NewPlaylistResponse = NewPlaylistResponses[keyof NewPlaylistResponses];

export type DelPlaylistData = {
  body?: never;
  path: {
    /**
     * The name of the playlist
     */
    playlist: string;
  };
  query?: never;
  url: "/api/playlist/{playlist}";
};

export type DelPlaylistErrors = {
  /**
   * The playlist wasn't found
   */
  404: Status;
  /**
   * Something went wrong
   */
  500: Status;
};

export type DelPlaylistError = DelPlaylistErrors[keyof DelPlaylistErrors];

export type DelPlaylistResponses = {
  /**
   * The requested playlist was deleted
   */
  200: Status;
};

export type DelPlaylistResponse = DelPlaylistResponses[keyof DelPlaylistResponses];

export type GetPlaylistData = {
  body?: never;
  path: {
    /**
     * The name of the playlist
     */
    playlist: string;
  };
  query?: never;
  url: "/api/playlist/{playlist}";
};

export type GetPlaylistErrors = {
  /**
   * The playlist wasn't found
   */
  404: Status;
  /**
   * Something went wrong
   */
  500: Status;
};

export type GetPlaylistError = GetPlaylistErrors[keyof GetPlaylistErrors];

export type GetPlaylistResponses = {
  /**
   * The requested playlist
   */
  200: Playlist;
};

export type GetPlaylistResponse = GetPlaylistResponses[keyof GetPlaylistResponses];

export type UpdatePlaylistData = {
  body: Playlist;
  path: {
    /**
     * The name of the playlist
     */
    playlist: string;
  };
  query?: never;
  url: "/api/playlist/{playlist}";
};

export type UpdatePlaylistErrors = {
  /**
   * Incomplete playlist supplied
   */
  422: Status;
  /**
   * Something went wrong
   */
  500: Status;
};

export type UpdatePlaylistError = UpdatePlaylistErrors[keyof UpdatePlaylistErrors];

export type UpdatePlaylistResponses = {
  /**
   * The requested playlist
   */
  200: Status;
};

export type UpdatePlaylistResponse = UpdatePlaylistResponses[keyof UpdatePlaylistResponses];

export type ListPlaylistsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/playlists";
};

export type ListPlaylistsErrors = {
  /**
   * Something went wrong
   */
  500: Status;
};

export type ListPlaylistsError = ListPlaylistsErrors[keyof ListPlaylistsErrors];

export type ListPlaylistsResponses = {
  /**
   * List of available playlists
   */
  200: Array<string>;
};

export type ListPlaylistsResponse = ListPlaylistsResponses[keyof ListPlaylistsResponses];

export type ListPlaylistsNumberedData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/playlists/numbered";
};

export type ListPlaylistsNumberedErrors = {
  /**
   * Something went wrong
   */
  500: Status;
};

export type ListPlaylistsNumberedError =
  ListPlaylistsNumberedErrors[keyof ListPlaylistsNumberedErrors];

export type ListPlaylistsNumberedResponses = {
  /**
   * List of available playlists
   */
  200: Array<NumberedPlaylist>;
};

export type ListPlaylistsNumberedResponse =
  ListPlaylistsNumberedResponses[keyof ListPlaylistsNumberedResponses];

export type NewSceneData = {
  body: NewScene;
  path?: never;
  query?: never;
  url: "/api/scene";
};

export type NewSceneErrors = {
  /**
   * Incomplete scene supplied
   */
  422: Status;
  /**
   * Something went wrong
   */
  500: Status;
};

export type NewSceneError = NewSceneErrors[keyof NewSceneErrors];

export type NewSceneResponses = {
  /**
   * The scene was created
   */
  201: Status;
};

export type NewSceneResponse = NewSceneResponses[keyof NewSceneResponses];

export type DelSceneData = {
  body?: never;
  path: {
    /**
     * The name of the scene
     */
    scene: string;
  };
  query?: never;
  url: "/api/scene/{scene}";
};

export type DelSceneErrors = {
  /**
   * The scene wasn't found
   */
  404: Status;
  /**
   * Something went wrong
   */
  500: Status;
};

export type DelSceneError = DelSceneErrors[keyof DelSceneErrors];

export type DelSceneResponses = {
  /**
   * The requested scene was deleted
   */
  200: Status;
};

export type DelSceneResponse = DelSceneResponses[keyof DelSceneResponses];

export type ListScenesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/scenes";
};

export type ListScenesErrors = {
  /**
   * Something went wrong
   */
  500: Status;
};

export type ListScenesError = ListScenesErrors[keyof ListScenesErrors];

export type ListScenesResponses = {
  /**
   * List of available scenes
   */
  200: Array<Scene>;
};

export type ListScenesResponse = ListScenesResponses[keyof ListScenesResponses];

export type GetSceneData = {
  body?: never;
  path: {
    /**
     * The name of the scene
     */
    scene: string;
  };
  query?: never;
  url: "/api/scenes/{scene}";
};

export type GetSceneErrors = {
  /**
   * The scene wasn't found
   */
  404: Status;
  /**
   * Something went wrong
   */
  500: Status;
};

export type GetSceneError = GetSceneErrors[keyof GetSceneErrors];

export type GetSceneResponses = {
  /**
   * The requested scene
   */
  200: Scene;
};

export type GetSceneResponse = GetSceneResponses[keyof GetSceneResponses];

export type UpdateSceneData = {
  body: NewScene;
  path: {
    /**
     * The name of the scene
     */
    scene: string;
  };
  query?: never;
  url: "/api/scenes/{scene}";
};

export type UpdateSceneErrors = {
  /**
   * Incomplete scene supplied
   */
  422: Status;
  /**
   * Something went wrong
   */
  500: Status;
};

export type UpdateSceneError = UpdateSceneErrors[keyof UpdateSceneErrors];

export type UpdateSceneResponses = {
  /**
   * The requested scene was updated
   */
  200: Status;
};

export type UpdateSceneResponse = UpdateSceneResponses[keyof UpdateSceneResponses];

export type NewScheduleData = {
  body: Schedule;
  path?: never;
  query?: never;
  url: "/api/schedule";
};

export type NewScheduleErrors = {
  /**
   * Incomplete schedule supplied
   */
  422: Status;
  /**
   * Something went wrong
   */
  500: Status;
};

export type NewScheduleError = NewScheduleErrors[keyof NewScheduleErrors];

export type NewScheduleResponses = {
  /**
   * The schedule was created
   */
  201: Status;
};

export type NewScheduleResponse = NewScheduleResponses[keyof NewScheduleResponses];

export type DelScheduleData = {
  body?: never;
  path: {
    /**
     * The name of the schedule
     */
    schedule: string;
  };
  query?: never;
  url: "/api/schedule/{schedule}";
};

export type DelScheduleErrors = {
  /**
   * The schedule wasn't found
   */
  404: Status;
  /**
   * Something went wrong
   */
  500: Status;
};

export type DelScheduleError = DelScheduleErrors[keyof DelScheduleErrors];

export type DelScheduleResponses = {
  /**
   * The requested schedule was deleted
   */
  200: Status;
};

export type DelScheduleResponse = DelScheduleResponses[keyof DelScheduleResponses];

export type GetScheduleData = {
  body?: never;
  path: {
    /**
     * The name of the schedule
     */
    schedule: string;
  };
  query?: never;
  url: "/api/schedule/{schedule}";
};

export type GetScheduleErrors = {
  /**
   * The schedule wasn't found
   */
  404: Status;
  /**
   * Something went wrong
   */
  500: Status;
};

export type GetScheduleError = GetScheduleErrors[keyof GetScheduleErrors];

export type GetScheduleResponses = {
  /**
   * The requested schedule
   */
  200: Schedule;
};

export type GetScheduleResponse = GetScheduleResponses[keyof GetScheduleResponses];

export type UpdateScheduleData = {
  body: Schedule;
  path: {
    /**
     * The name of the schedule
     */
    schedule: string;
  };
  query?: never;
  url: "/api/schedule/{schedule}";
};

export type UpdateScheduleErrors = {
  /**
   * Incomplete schedule supplied
   */
  422: Status;
  /**
   * Something went wrong
   */
  500: Status;
};

export type UpdateScheduleError = UpdateScheduleErrors[keyof UpdateScheduleErrors];

export type UpdateScheduleResponses = {
  /**
   * The requested schedule was updated
   */
  200: Status;
};

export type UpdateScheduleResponse = UpdateScheduleResponses[keyof UpdateScheduleResponses];

export type ListSchedulesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/schedules";
};

export type ListSchedulesErrors = {
  /**
   * Something went wrong
   */
  500: Status;
};

export type ListSchedulesError = ListSchedulesErrors[keyof ListSchedulesErrors];

export type ListSchedulesResponses = {
  /**
   * List of available schedules
   */
  200: Array<Schedule>;
};

export type ListSchedulesResponse = ListSchedulesResponses[keyof ListSchedulesResponses];

export type DelSequenceData = {
  body?: never;
  path: {
    /**
     * The sequence to download
     */
    filename: string;
  };
  query?: never;
  url: "/api/sequence/{filename}";
};

export type DelSequenceErrors = {
  /**
   * Something went wrong
   */
  500: Status;
};

export type DelSequenceError = DelSequenceErrors[keyof DelSequenceErrors];

export type DelSequenceResponses = {
  /**
   * The sequence was removed
   */
  200: Status;
};

export type DelSequenceResponse = DelSequenceResponses[keyof DelSequenceResponses];

export type GetSequenceData = {
  body?: never;
  path: {
    /**
     * The sequence to download
     */
    filename: string;
  };
  query?: never;
  url: "/api/sequence/{filename}";
};

export type GetSequenceErrors = {
  /**
   * The sequence wasn't found
   */
  404: Status;
  /**
   * Something went wrong
   */
  500: Status;
};

export type GetSequenceError = GetSequenceErrors[keyof GetSequenceErrors];

export type GetSequenceResponses = {
  /**
   * The requested sequence
   */
  200: Blob | File;
};

export type GetSequenceResponse = GetSequenceResponses[keyof GetSequenceResponses];

export type GetSequenceMetaData = {
  body?: never;
  path: {
    /**
     * The sequence to download
     */
    filename: string;
  };
  query?: never;
  url: "/api/sequence/{filename}/meta";
};

export type GetSequenceMetaErrors = {
  /**
   * The sequence wasn't found
   */
  404: Status;
  /**
   * Something went wrong
   */
  500: Status;
};

export type GetSequenceMetaError = GetSequenceMetaErrors[keyof GetSequenceMetaErrors];

export type GetSequenceMetaResponses = {
  /**
   * The requested sequence
   */
  200: SequenceMeta;
};

export type GetSequenceMetaResponse = GetSequenceMetaResponses[keyof GetSequenceMetaResponses];

export type ListSequencesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/sequences";
};

export type ListSequencesErrors = {
  /**
   * Something went wrong
   */
  500: Status;
};

export type ListSequencesError = ListSequencesErrors[keyof ListSequencesErrors];

export type ListSequencesResponses = {
  /**
   * The requested sequence
   */
  200: Array<string>;
};

export type ListSequencesResponse = ListSequencesResponses[keyof ListSequencesResponses];

export type SystemInfoData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/system/info";
};

export type SystemInfoResponses = {
  200: SystemInfo;
};

export type SystemInfoResponse = SystemInfoResponses[keyof SystemInfoResponses];

export type GetTestPatternData = {
  body: Sequence;
  path?: never;
  query: {
    /**
     * Lenght of the LED chain
     */
    length: number;
  };
  url: "/api/test_pattern";
};

export type GetTestPatternErrors = {
  /**
   * Something went wrong
   */
  500: Status;
};

export type GetTestPatternError = GetTestPatternErrors[keyof GetTestPatternErrors];

export type GetTestPatternResponses = {
  /**
   * The pattern of RGB to display
   */
  200: Array<Color>;
};

export type GetTestPatternResponse = GetTestPatternResponses[keyof GetTestPatternResponses];

export type FileUploadData = {
  body: FileUpload;
  path?: never;
  query?: never;
  url: "/api/upload";
};

export type FileUploadErrors = {
  /**
   * Unrecognized file type
   */
  400: Status;
  /**
   * Something went wrong
   */
  500: Status;
};

export type FileUploadError = FileUploadErrors[keyof FileUploadErrors];

export type FileUploadResponses = {
  /**
   * File uploaded successfully
   */
  200: Status;
};

export type FileUploadResponse = FileUploadResponses[keyof FileUploadResponses];

export type FppCommandData = {
  body?: never;
  path?: never;
  query: {
    /**
     * The FFP command
     */
    command: string;
    /**
     * The file to move
     */
    file: string;
  };
  url: "/fppxml.php";
};

export type FppCommandErrors = {
  /**
   * Unrecognized command
   */
  400: Status;
  /**
   * File doesn't exist
   */
  404: Status;
};

export type FppCommandError = FppCommandErrors[keyof FppCommandErrors];

export type FppCommandResponses = {
  /**
   * File exists
   */
  200: Status;
};

export type FppCommandResponse = FppCommandResponses[keyof FppCommandResponses];
